### ISSUE TITLE
Incorrect log message in client

### ISSUE THREAD

**Issue by astinnos** [dragonchain-inc/dragonchain-sdk-node#70]
`if (!dragonchainId) {
      logger.debug('Dragonchain ID explicitly provided, will not search env/disk')
      dragonchainId = CredentialService.getDragonchainId()
 }`

Log message should be "Dragonchain ID not explicitly provided, will search env/disk"

**Comment by deanshelton913** [comment]
Good catch. We are gonna put in a patch for this.
Also: feel free to contribute. We have added a contributing.md file at root!

**Comment by regan-karlewicz** [comment]
Fixed by #77
