### ISSUE TITLE
Missing examples for most methods

### ISSUE THREAD

**Issue by jlubeck** [dragonchain-inc/dragonchain-sdk-node#73]
It would be nice to have examples for all the methods and not just get a block or query a transaction.

Specially for creating new contracts and transactions since they seem to be the most complex ones

**Comment by astinnos** [comment]
A tutorial on creating a custom contract can be found here https://github.com/dragonchain-inc/custom-contract-node-sdk

**Comment by jlubeck** [comment]
This is great, should definitely be part of the README.md file!

**Comment by jlubeck** [comment]
I would still love to see examples for most methods, and not just for the few that are on that other repo.
